### ISSUE TITLE
object tracking代码

### ISSUE THREAD

**Issue by Iriya99** [Dawn-LX/OpenVoc-VidVRD#1]
请问object tracking部分是没有公布代码吗？tracklet是用什么模型提取的呢？

**Comment by Dawn-LX** [comment]
we use Seq-NMS to build object tracklets, refer to https://github.com/tmoopenn/seq-nms

As for how to moidify the code to VidVRD setting, we follow the code of this paper "Video Visual Relation Detection via Iterative Inference ACM MM 2021" (shangxin@comp.nus.edu.sg)

**Comment by Iriya99** [comment]
How can I test the model on my own video?

**Comment by Dawn-LX** [comment]
> How can I test the model on my own video?

What do you mean? test only the quality of object tracklets ?

**Comment by Dawn-LX** [comment]
Please refer to this repo [VidSGG-TrajDataPrepare](https://github.com/Dawn-LX/VidSGG-TrajDataPrepare) for how to prepare the above traj data, including 1)detect bbox --> 2)object tracking --> 3)extract RoI features.

**Comment by Iriya99** [comment]
Thanks very much.
