### ISSUE TITLE
[Errno 2] No such file or directory: 'datasets/gt_jsons/VidVRDtest_segment_gts.json'

### ISSUE THREAD

**Issue by ZiyueWu59** [Dawn-LX/OpenVoc-VidVRD#2]
Hi, could you help me how to obtain the file `VidVRDtest_segment_gts.json` used in `train_relation_cls.py` ?
Thank you very much!

**Comment by Dawn-LX** [comment]
> Hi, could you help me how to obtain the file `VidVRDtest_segment_gts.json` used in `train_relation_cls.py` ? Thank you very much!

I have update the repo, please refer to `datasets/gt_jsons/readme.md` to build `VidVRDtest_segment_gts.json` and other `*_gts.json` files

https://github.com/Dawn-LX/OpenVoc-VidVRD/blob/master/datasets/gt_jsons/readme.md
