### ISSUE TITLE
How to extract RoI features

### ISSUE THREAD

**Issue by QiueY514** [Dawn-LX/OpenVoc-VidVRD#3]
Hi, thank you for your excellent work!
The released RoI features have been averaged of all the bounding boxes along the temporal axis of the tracklets. So could you release the RoI features for each bounding box without averaging? Thank you very much.

**Comment by Dawn-LX** [comment]
we did not store the frame-level RoI features. But we can release the code for extracting trackets' RoI features.  Maybe 3~5 days later.

**Comment by ZiyueWu59** [comment]
> we did not store the frame-level RoI features. But we can release the code for extracting trackets' RoI features. Maybe 3~5 days later.

Thank you for your generous help!

**Comment by QiueY514** [comment]
> we did not store the frame-level RoI features. But we can release the code for extracting trackets' RoI features. Maybe 3~5 days later.

Thank you for your generous sharing!

**Comment by Dawn-LX** [comment]
> > we did not store the frame-level RoI features. But we can release the code for extracting trackets' RoI features. Maybe 3~5 days later.
> 
> Thank you for your generous sharing!

Hi, you can refer to this repo [VidSGG-TrajDataPrepare](https://github.com/Dawn-LX/VidSGG-TrajDataPrepare) for traj data preparing. It include 3 stages: 1)detect bbox --> 2)object tracking --> 3)extract RoI features.

**Comment by QiueY514** [comment]
> > > we did not store the frame-level RoI features. But we can release the code for extracting trackets' RoI features. Maybe 3~5 days later.
> > 
> > 
> > Thank you for your generous sharing!
> 
> Hi, you can refer to this repo [VidSGG-TrajDataPrepare](https://github.com/Dawn-LX/VidSGG-TrajDataPrepare) for traj data preparing. It include 3 stages: 1)detect bbox --> 2)object tracking --> 3)extract RoI features.

Thank you for your shared code! It helps me a lot.
